FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Models/Delivery.cs
using FleetManagementWebAplication.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FleetManagementWebApplication.Models
{
    public class Delivery
    {
        [Required]
        public long Id { get; set; }
        [Required]
        public DateTime Time { get; set; }

        public Company Company { get; set; } 
        public Client Client { get; set; }
        public Vehicle Vehicle { get; set; }
        public Driver Driver { get; set; }

        [Required]
        public double SourceLongtitude { get; set; }
        [Required]
        public double SourceLatitude { get; set; }
        
        public string SourceCity { get; set; }
        [Required]
        public double DestinationLongtitude { get; set; }
        [Required]
        public double DestinationLatitude { get; set; }
        
        public string DestinationCity { get; set; }
        [Required]
        public int Quantity { get; set; }
      
        public bool Answered { get; set; } = false;
        public bool Started { get; set; } = false;
        public bool Finished { get; set; } = false;

        public float OptimalDistance { get; set; }
        public int OptimalTime { get; set; }
        public float OptimalFuelConsumption { get; set; }

    }
}

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Controllers/DeliveriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FleetManagementWebApplication.Models;

namespace FleetManagementWebApplication.Controllers
{
    public class DeliveriesController : FleetController
    {
        

        public DeliveriesController(ApplicationDbContext context):base(context)
        {
            
        }

        // GET: Deliveries
        public async Task<IActionResult> Index()
        {
            return View(await _context.Deliveries.ToListAsync());
        }
        public async Task<IActionResult> DriversDeliveries(long Id)
        {
            if (!LogedIn())
                return RedirectToRoute("Home");

            List<SelectListItem> Drivers = new List<SelectListItem>();
            Driver[] drivers = _context.Drivers.Where(d => d.Company.Id == CompanyId).ToArray();
            foreach (Driver d in drivers)
            {
                if (d.Id == Id)
               Drivers.Add(new SelectListItem { Value = "" + d.Id, Text = d.Name + ", username: " + d.Username, Selected =true });
                else
               Drivers.Add(new SelectListItem { Value = "" + d.Id, Text =d.Name+", username: "+d.Username });
            }
            ViewData["drivers"] = Drivers;
           
            return View(await _context.Deliveries.Where(d=>d.Driver.Id==Id).Include(d=>d.Client).Include(d=>d.Vehicle).ToListAsync());
        }


        public async Task<IActionResult> ClientsDeliveries(long Id)
        {
            if (!LogedIn())
                return RedirectToRoute("Home");

            List<SelectListItem> Clients = new List<SelectListItem>();
            Client[] clients = _context.Deliveries.Where(d => d.Company.Id == CompanyId).Select(d => d.Client)
                                                         .Union(_context.Clients.Where(c => c.Company.Id == CompanyId)).ToArray();
            foreach (Client c in clients)
            {
                if (c.Id == Id)
                   Clients.Add(new SelectListItem { Value = "" + c.Id, Text = c.Name + ", username: " + c.Username, Selected = true });
                else
                   Clients.Add(new SelectListItem { Value = "" + c.Id, Text = c.Name + ", username: " +c.Username });
            }
            ViewData["clients"] = Clients;

            return View(await _context.Deliveries.Where(d => d.Client.Id == Id).Include(d => d.Driver).Include(d => d.Vehicle).ToListAsync());
        }




        // POST: Deliveries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var delivery = await _context.Deliveries.FindAsync(id);
            _context.Deliveries.Remove(delivery);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeliveryExists(long id)
        {
            return _context.Deliveries.Any(e => e.Id == id);
        }
    }
}

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Deliveries/ClientsDeliveries.cshtml
@model IEnumerable<Delivery>

@{
    ViewData["Title"] = "Clients Deliveries";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
    List<SelectListItem> clients=(List<SelectListItem>)ViewData["clients"];

}
    <div class="box-wrapper">
        <div class="box effect6">
            <h3>Clients Deliveries</h3>
            <div class="w3-container w3-padding">
                <form asp-controller="Deliveries" asp-action="ClientsDeliveries" >
                    <div  style="padding:10px 20px;text-align:right;width:100%">
                    <table cellspacing="15px" style="border:2px solid grey;border-radius:20px;background-color: rgb(250,250,250);" align="right" ><tr>
                            <td class="td1" style="padding-left:20px;color:rgb(50,50,50);font-size:25px;text-align:right;"> Select a client: </td>                      
                            <td class="td1"><select  name="Id" style="height:50px;border:2px solid grey;border-radius:15px;padding-left:10px;padding-right:10px;"
                                                               asp-items="@clients"  onchange="this.form.submit();"></select> </td>                
                        </tr></table>
                        </div>
                </form>
                <center>
                    <br /><br />
                    <br /><br />
                    <table width="90%" style="padding:10px 10px">
                        <tr>
                            <th>Date and Time</th>
                            <th>Source City</th>
                            <th>Destination City</th>
                            <th>Vehicle</th>
                            <th>Driver</th>
                            <th>Quantity</th>
                            <th>Status</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td class="date">
                                @item.Time
                            </td>
                            <td>
                                @item.SourceCity
                            </td>
                            <td>
                                @item.DestinationCity
                            </td>
                            <td>
                                @item.Vehicle.Make @item.Vehicle.Model @item.Vehicle.LicensePlate
                            </td>
                            <td>
                                @item.Driver.Name
                            </td>
                            <td>
                                @item.Quantity
                            </td>
                            @if(item.Finished)
                        {
                            <td style="color:white;background-color:red">Finished</td>
                         }
                        else
                        {
                             if(item.Started)
                            {
                            <td style="color:white;background-color:forestgreen">Started</td>
                            }
                            else{
                            <td style="color:white;background-color:blue">Answered</td>
                            }
                        }


                        </tr>
                     }

                    </table>

                </center>
            </div>
        </div>
    </div>
        

        <style>
            tr, th {
                text-align: left
            }

            th {
                background-color: green;
                color: white;
              padding: 2px 10px;
            }

            .date {
                background-color: cyan;
                width: 200px;
                color: black;
            }

            
            td {
            background-color:rgb(230,230,230);
                padding-left: 10px;
            }

            .td1 {
                text-align: center;
                background-color:initial;
                padding: 10px 10px;
                color: white;
                font-size: 18px;
            }

          
         

            .box {
                text-align: left;
                position: relative;
                top: 12px;
                padding: 10px 30px;
                width: 95%;
                padding-bottom: 200px;
                background: #FFF;
            }

            
              
        </style>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Deliveries/Create.cshtml
@model FleetManagementWebApplication.Models.Delivery

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
}

<h1>Create</h1>

<h4>Delivery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceLongtitude" class="control-label"></label>
                <input asp-for="SourceLongtitude" class="form-control" />
                <span asp-validation-for="SourceLongtitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceLatitude" class="control-label"></label>
                <input asp-for="SourceLatitude" class="form-control" />
                <span asp-validation-for="SourceLatitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceCity" class="control-label"></label>
                <input asp-for="SourceCity" class="form-control" />
                <span asp-validation-for="SourceCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationLongtitude" class="control-label"></label>
                <input asp-for="DestinationLongtitude" class="form-control" />
                <span asp-validation-for="DestinationLongtitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationLatitude" class="control-label"></label>
                <input asp-for="DestinationLatitude" class="form-control" />
                <span asp-validation-for="DestinationLatitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationCity" class="control-label"></label>
                <input asp-for="DestinationCity" class="form-control" />
                <span asp-validation-for="DestinationCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Answered" /> @Html.DisplayNameFor(model => model.Answered)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Started" /> @Html.DisplayNameFor(model => model.Started)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Finished" /> @Html.DisplayNameFor(model => model.Finished)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="OptimalDistance" class="control-label"></label>
                <input asp-for="OptimalDistance" class="form-control" />
                <span asp-validation-for="OptimalDistance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptimalTime" class="control-label"></label>
                <input asp-for="OptimalTime" class="form-control" />
                <span asp-validation-for="OptimalTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptimalFuelConsumption" class="control-label"></label>
                <input asp-for="OptimalFuelConsumption" class="form-control" />
                <span asp-validation-for="OptimalFuelConsumption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Deliveries/Delete.cshtml
@model FleetManagementWebApplication.Models.Delivery

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delivery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SourceLongtitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SourceLongtitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SourceLatitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SourceLatitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SourceCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SourceCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationLongtitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationLongtitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationLatitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationLatitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Answered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Answered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Started)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Started)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Finished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Finished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OptimalDistance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OptimalDistance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OptimalTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OptimalTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OptimalFuelConsumption)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OptimalFuelConsumption)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Deliveries/Details.cshtml
@model FleetManagementWebApplication.Models.Delivery

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Delivery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SourceLongtitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SourceLongtitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SourceLatitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SourceLatitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SourceCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SourceCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationLongtitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationLongtitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationLatitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationLatitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DestinationCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Answered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Answered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Started)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Started)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Finished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Finished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OptimalDistance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OptimalDistance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OptimalTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OptimalTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OptimalFuelConsumption)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OptimalFuelConsumption)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Deliveries/DriversDeliveries.cshtml
@model IEnumerable<Delivery>

@{
    ViewData["Title"] = "Drivers Deliveries";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
    List<SelectListItem> drivers=(List<SelectListItem>)ViewData["drivers"];

}
    <div class="box-wrapper">
        <div class="box effect6">
            <h3>Drivers Deliveries</h3>
            <div class="w3-container w3-padding">
                <form asp-controller="Deliveries" asp-action="DriversDeliveries" >
                    <div  style="padding:10px 20px;text-align:right;width:100%">
                    <table cellspacing="15px" style="border:2px solid grey;border-radius:20px;background-color: rgb(250,250,250);" align="right" ><tr>
                            <td class="td1" style="padding-left:20px;color:rgb(50,50,50);font-size:25px;text-align:right;"> Select a driver: </td>                      
                            <td class="td1"><select  name="Id" style="height:50px;border:2px solid grey;border-radius:15px;padding-left:10px;padding-right:10px;"
                                                               asp-items="@drivers"  onchange="this.form.submit();"></select> </td>                
                        </tr></table>
                        </div>
                </form>
                <center>
                    <br /><br />
                    <br /><br />
                    <table width="90%" style="padding:10px 10px">
                        <tr>
                            <th>Date and Time</th>
                            <th>Source City</th>
                            <th>Destination City</th>
                            <th>Vehicle</th>
                            <th>Client</th>
                            <th>Quantity</th>
                            <th>Status</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td class="date">
                                @item.Time
                            </td>
                            <td>
                                @item.SourceCity
                            </td>
                            <td>
                                @item.DestinationCity
                            </td>
                            <td>
                                @item.Vehicle.Make @item.Vehicle.Model @item.Vehicle.LicensePlate
                            </td>
                            <td>
                                @item.Client.Name
                            </td>
                            <td>
                                @item.Quantity
                            </td>
                            @if(item.Finished)
                        {
                            <td style="color:white;background-color:red">Finished</td>
                         }
                        else
                        {
                             if(item.Started)
                            {
                            <td style="color:white;background-color:forestgreen">Started</td>
                            }
                            else{
                            <td style="color:white;background-color:blue">Answered</td>
                            }
                        }


                        </tr>
                     }

                    </table>

                </center>
            </div>
        </div>
    </div>
        

        <style>
            tr, th {
                text-align: left
            }

            th {
                background-color: green;
                color: white;
              padding: 2px 10px;
            }

            .date {
                background-color: cyan;
                width: 200px;
                color: black;
            }

            
            td {
            background-color:rgb(230,230,230);
                padding-left: 10px;
            }

            .td1 {
                text-align: center;
                background-color:initial;
                padding: 10px 10px;
                color: white;
                font-size: 18px;
            }

            .box {
                text-align: left;
                position: relative;
                top: 12px;
                padding: 10px 30px;
                width: 95%;
                padding-bottom: 200px;
                background: #FFF;
            }

            
              
        </style>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Deliveries/Edit.cshtml
@model FleetManagementWebApplication.Models.Delivery

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
}

<h1>Edit</h1>

<h4>Delivery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceLongtitude" class="control-label"></label>
                <input asp-for="SourceLongtitude" class="form-control" />
                <span asp-validation-for="SourceLongtitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceLatitude" class="control-label"></label>
                <input asp-for="SourceLatitude" class="form-control" />
                <span asp-validation-for="SourceLatitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SourceCity" class="control-label"></label>
                <input asp-for="SourceCity" class="form-control" />
                <span asp-validation-for="SourceCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationLongtitude" class="control-label"></label>
                <input asp-for="DestinationLongtitude" class="form-control" />
                <span asp-validation-for="DestinationLongtitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationLatitude" class="control-label"></label>
                <input asp-for="DestinationLatitude" class="form-control" />
                <span asp-validation-for="DestinationLatitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationCity" class="control-label"></label>
                <input asp-for="DestinationCity" class="form-control" />
                <span asp-validation-for="DestinationCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Answered" /> @Html.DisplayNameFor(model => model.Answered)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Started" /> @Html.DisplayNameFor(model => model.Started)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Finished" /> @Html.DisplayNameFor(model => model.Finished)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="OptimalDistance" class="control-label"></label>
                <input asp-for="OptimalDistance" class="form-control" />
                <span asp-validation-for="OptimalDistance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptimalTime" class="control-label"></label>
                <input asp-for="OptimalTime" class="form-control" />
                <span asp-validation-for="OptimalTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptimalFuelConsumption" class="control-label"></label>
                <input asp-for="OptimalFuelConsumption" class="form-control" />
                <span asp-validation-for="OptimalFuelConsumption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>