Clinic/Clinic/Models/Consultation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Clinic.Models
{
    public class Consultation
    {
        [Required]
        public long Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        [StringLength(100)]
        public string Type { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        [StringLength(20)]
        public string Temperature { get; set; }
        [Required]
        [StringLength(20)]
        public string BloodPressure { get; set; }
        [Required]
        public string Symptoms { get; set; }
        [Required]
        public string Diagnosis{ get; set; }
        [Required]
        public string Treatment { get; set; }
        [Required]
        [StringLength(20)]
        public string Cost { get; set; }
        [Required]
        public bool InsuranceConfirmation { get; set; } = false;
        public Patient Patient { get; set; }
        public Doctor Doctor { get; set; }
    }
}

Clinic/Clinic/Controllers/ConsultationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clinic.Data;
using Clinic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Clinic.Controllers
{
    public class ConsultationsController : ClinicController
    {
     
 public ConsultationsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
            :base( context, userManager)
        {
           
        }
        [Authorize(Roles = "Doctor,Admin")]
        public async Task<IActionResult> Index()
        {
             string Id = _userManager.GetUserId(User);

            if (User.IsInRole("Doctor"))
            {
               
                return View(await _context.Consultations.Where(c=>c.Doctor.User.Id==Id)
                                                            .Include(c => c.Patient).ToListAsync());
            }
          
            return View(await _context.Consultations.Include(c => c.Patient).Include(c=>c.Doctor).ToListAsync());
        }

        [Authorize(Policy = "Patient")]
        public async Task<IActionResult> SearchPatientsConsultations(SearchConsultaion search)
        {
            var query = _context.Consultations.Where(c=>c.Patient.User.Id == _userManager.GetUserId(User))
                                                                           .Include(a => a.Doctor).ToArray();

            if (search.Doctor != 0)
                query = query.Where(d => d.Doctor.Id == search.Doctor).ToArray();
            if (search.Title != null)
                query = query.Where(d => d.Title == search.Title).ToArray();
            if (search.Type != null)
                query = query.Where(d => d.Type == search.Type).ToArray();
            if (search.Order == "desc")
                query = query.OrderByDescending(d => d.Date).ToArray();
            else
                query = query.OrderBy(d => d.Date).ToArray();
            search.Consultations = query;

            search.FillDoctors(_context.Doctor_Patients.Where(r => r.Patient.User.Id == _userManager.GetUserId(User))
                                                                                            .Select(r => r.Doctor).Distinct().ToArray());
            return View(search);
        }

        [Authorize(Policy = "Doctor")]
        public async Task<IActionResult> SearchDoctorsConsultations(SearchConsultaion search)
        {
            var query = _context.Consultations.Where(c => c.Doctor.User.Id == _userManager.GetUserId(User))
                                                                            .Include(a => a.Patient).ToArray();

            if (search.Patient != 0)
                query = query.Where(d => d.Patient.Id == search.Patient).ToArray();
            if (search.Title != null)
                query = query.Where(d => d.Title == search.Title).ToArray();
            if (search.Type != null)
                query = query.Where(d => d.Type == search.Type).ToArray();
            if (search.Order == "desc")
                query = query.OrderByDescending(d => d.Date).ToArray();
            else
                query = query.OrderBy(d => d.Date).ToArray();
            search.Consultations = query;

            search.FillPatients(_context.Doctor_Patients.Where(r=>r.Doctor.User.Id== _userManager.GetUserId(User))
                                                                                            .Select(r=>r.Patient).Distinct().ToArray());
            return View(search);
        }

        [Authorize(Roles = "Patient")]
        public IActionResult Treatment()
        {
            Consultation[] consultations = _context.Consultations
                                                                                .Include(c => c.Doctor)
                                                                                .Where(c => c.Patient.User.Id == _userManager.GetUserId(User))
                                                                                .ToArray();
            Dictionary<Doctor, List<Consultation>> doctors=new Dictionary<Doctor, List<Consultation>>();
            foreach (Consultation c in consultations)
                if (!doctors.ContainsKey(c.Doctor))
                    doctors[c.Doctor] = new List<Consultation>() { c };
                else
                    doctors[c.Doctor].Add(c);

           
            ViewBag.consultaions = consultations;
            ViewBag.doctors = doctors;
            return View();
        }




        [Authorize(Roles = "Assistant,Doctor")]
        public IActionResult Create()
        {
            AddConsultation model = new AddConsultation();
            Patient[] Ps = _context.Patients.ToArray();
            model.Patients = new SelectListItem[Ps.Length];
            for (int i = 0; i <model.Patients.Length; i++)
            {
               model.Patients[i] = new SelectListItem { Value = ""+Ps[i].Id, Text = Ps[i].DisplayName };
            }
           
            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Assistant,Doctor")]
        public async Task<IActionResult> Create(AddConsultation addConsultation)
        {
           

            if (ModelState.IsValid)
            {
                Consultation consultation = new Consultation()
                {
                   Patient = _context.Patients.Where(p => p.Id == addConsultation.SelectedPatientId)
                                                                    .Include(p=>p.InsuranceCompany).Single<Patient>(),
                    Doctor = _context.Doctors.Single(d=>d.User.Id==_userManager.GetUserId(User)),
                    Title = addConsultation.Title,
                    Type=addConsultation.Type,
                    Date = DateTime.Now,
                    Temperature = addConsultation.Temperature,
                    BloodPressure=addConsultation.BloodPressure,
                    Symptoms =addConsultation.Symptoms,
                    Diagnosis = addConsultation.Diagnosis,
                    Treatment= addConsultation.Treatment,
                    Cost = addConsultation.Cost,
                    InsuranceConfirmation = addConsultation.InsuranceConfirmation
                 };
                _context.Add(consultation);
             
                Doctor_Patient Relation = new Doctor_Patient()
                {
                    Doctor = consultation.Doctor,
                    Patient = consultation.Patient
                };
                _context.Add(Relation);

                Report report = new Report()
                {
                    Date = consultation.Date,
                    Price = consultation.Cost,
                    Doctor = consultation.Doctor,
                    Patient = consultation.Patient,
                    Consultation = consultation,
                    Insurance = consultation.Patient.InsuranceCompany

                };
                _context.Add(report);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(SearchDoctorsConsultations));
            }
            Patient[] Ps = _context.Patients.ToArray();
            SelectListItem[] Patients = new SelectListItem[Ps.Length + 1];
            Patients[0] = new SelectListItem { Value = "", Text = "Select the patient" };
            for (int i = 0; i < Patients.Length - 1; i++)
            {
                Patients[i + 1] = new SelectListItem { Value = ""+Ps[i].Id, Text = Ps[i].DisplayName };
            }
            ViewData["Patients"] = Patients;
            return View(addConsultation);
        }

        [Authorize(Policy = "Doctor")]
        public async Task<IActionResult> Edit(long? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var consultation = await _context.Consultations.Where(c=>c.Id==id).FirstAsync();
            if (consultation == null)
            {
                return NotFound();
            }

            return View(consultation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Doctor")]
        public async Task<IActionResult> Edit(long id, Consultation consultation)
        {
           

            if (id != consultation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    _context.Update(consultation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsultationExists(consultation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(SearchDoctorsConsultations));
            }
            return View(consultation);
        }

   

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Doctor")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
           

            var consultation = await _context.Consultations.FindAsync(id);
            Report[] reports = _context.Report.Where(c => c.Consultation.Id == id).ToArray();
            _context.Report.RemoveRange(reports);
            _context.Consultations.Remove(consultation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConsultationExists(long id)
        {
            return _context.Consultations.Any(e => e.Id == id);

Clinic/Clinic/Views/Consultations/Create.cshtml
@model Clinic.Models.AddConsultation

@{
    ViewData["Title"] = "Create";
    
}

<link rel="stylesheet" href="~/css/window.css" />
<div class="window-wrapper">
    <div class="window">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="header">
                Add Consultation
                <a href="/home" class="btn-X">X</a>
            </div>
            <div class="body">
                <div class="row">
                    <div class="col-lg-3 ">
                        <div class="table1">
                            <div class="form-group">
                                <label class="control-label">Patient</label>
                                <select asp-for="@Model.SelectedPatientId" asp-items="@Model.Patients" class="form-control" style="border-radius:20px;"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Type" class="control-label"></label>
                                <select asp-for="Type" asp-items="@Model.Types" class="form-control" style="border-radius:20px;"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Temperature" class="control-label"></label>
                                <input asp-for="Temperature" class="form-control" />
                                <span asp-validation-for="Temperature" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BloodPressure" class="control-label"></label>
                                <input asp-for="BloodPressure" class="form-control" />
                                <span asp-validation-for="BloodPressure" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Cost" class="control-label"></label>
                                <input asp-for="Cost" class="form-control" />
                                <span asp-validation-for="Cost" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input asp-for="InsuranceConfirmation"  /> Insurance Confirmation
                                <span asp-validation-for="InsuranceConfirmation" class="text-danger"></span>
                            </div>

                        </div>

                    </div>
                    <div class="col-lg-9">
                        <div class="table1">

                            <div class="form-group">
                                <label asp-for="Symptoms" class="control-label"></label><br />
                                <textarea asp-for="Symptoms" rows="4"></textarea>
                                <span asp-validation-for="Symptoms" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Diagnosis" class="control-label"></label><br />
                                <textarea asp-for="Diagnosis" rows="4"></textarea>
                                <span asp-validation-for="Diagnosis" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Treatment" class="control-label"></label><br />
                                <textarea asp-for="Treatment" rows="4" cols="90%"></textarea>
                                <span asp-validation-for="Treatment" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="footer">


                <input type="submit" value="Save" class="btn btn-success" />


            </div>
        </form>
    </div>
</div>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>@ViewData["Error"]</h1>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    ;
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

<style>
    .top {
        margin-top: 0px;
        height: 78px;
    }

    td {
        padding: 2px 30px;
    }

    select, textarea, input[type="text"] {
        width: 100%;
        border: 1px solid #999999;
        border-radius: 30px;
        padding: 10px;
    }
</style>

Clinic/Clinic/Views/Consultations/SearchDoctorsConsultations.cshtml
@model SearchConsultaion

@{
    ViewData["Title"] = "Search";
    SelectListItem Asc = new SelectListItem() { Value = "asc", Text = "Ascending" };
    SelectListItem Desc = new SelectListItem() { Value = "desc", Text = "Descending" };
    if (Model.Order == "desc")
    {
        Desc.Selected = true;
    }
    else
    {
        Asc.Selected = true;
    }
    SelectListItem[] Orders = { Asc, Desc };
   


}
<style>
    .window {
        width: initial;
    }

    .col-lg-9 {
        padding-left: 10px;
    }

    .col-lg-3 {
        text-align: left;
    }
</style>
<div class="window-wrapper" style="padding-top:10px;">
    <div style="text-align:left;display:inline-block;min-width:80%;">
        <div class="row">
            <div class="col-lg-3 col-md-3 ">
                <div class="window">
                    <form asp-action="Search" method="get">
                        <div class="header">
                            Search 
                        </div>
                        <div class="body" style="padding-left:10px;padding-right:10px;">
                            <div class="form-group">
                                <label asp-for="Patient" class="control-label"></label>
                                <select asp-for="Patient" class="form-control ss" asp-items="@Model.Patients"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" value="@Model.Title" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Type</label>
                                <input asp-for="Type" class="form-control" value="@Model.Type" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Order</label>
                                <select asp-for="Order" class="form-control ss" asp-items="@Orders"></select>
                            </div>


                        </div>
                        <div class="footer">
                            <button type="submit" class="btn btn-success">Search</button>
                        </div>
                    </form>
                </div>

            </div>
            <div class="col-lg-9 col-md-9 ">
                <div class="window" style="width:100%;">
                    <div class="header">
                        Consultaions
                    </div>
                    <div class="body" style="min-height:470px;">
                        <div style="font-size:15px;padding-bottom:10px;">Click on any search entry to view the details of the consultation</div>

                        @foreach (var item in Model.Consultations)
                        {

                            <form asp-action="Details" asp-route-id="@item.Id" onclick="Show(@item.Id);">
                                <div class="srch-div" style="width:90%;margin-bottom:3px;">
                                    <table style="width:100%">
                                        <tr>
                                            <td style="width:20%">
                                                <img src="~/images/@item.Patient.Image" class="srch-img" />
                                            </td>
                                            <td>
                                                <div style="padding-left:20px;padding-bottom:5px;padding-top:5px;font-size:15px;">

                                                    <div style="font-size:20px;color:rgb(0,0,250);">@Html.DisplayFor(modelItem => item.Title)</div>

                                                    Patient : @item.Patient.DisplayName
                                                    <br />
                                                    Type:  @Html.DisplayFor(modelItem => item.Type)
                                                    <br />
                                                    Date:  @Html.DisplayFor(modelItem => item.Date)
                                                    <br />
                                                    Cost: @item.Cost $
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </form>
                            <div class="modal fade" id="@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle" style="font-size:25px">Consultation Details </h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body" style="padding-bottom:40px;">
                                            <div class="row">
                                                <div class="col-lg-7">
                                                    <h2>@item.Title</h2>
                                                    <div>Patient: @item.Patient.DisplayName</div>
                                                    <div>Date: @item.Date</div>
                                                    <div>Type: @item.Type</div>
                                                    <div>Temperature: @item.Temperature</div>
                                                    <div>Blood Pressure: @item.BloodPressure</div>
                                                    <div>Coste: @item.Cost</div>
                                                </div>
                                                <div class="col-lg-5">
                                                    <img src="~/images/@item.Patient.Image" width="250" height="250" style="border-radius:5px;" />
                                                </div>
                                                <div class="col-lg-7">
                                                    Symptoms: <p>@item.Symptoms</p>
                                                    Diagnosis: <p>@item.Diagnosis</p>
                                                  Treatment:<p>@item.Treatment</p> 
                                                   
                                                </div>                                       
                                                <div class="col-lg-5">
                                                        <br />
                                                        <br />
                                                        <a asp-controller="Consultations" asp-action="Edit" class="a2" asp-route-id="@item.Id">Edit Consultation</a><br />
                                                        <a href="javascript:void(0)" class="a2" onclick="Remove('@item.Id');" >Remove Consultation</a>

                                                    </div>
                                                </div>
                                                <div class="modal fade" id="@("C"+item.Id)" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                                        <div class="modal-content" style="border-radius:10px;">
                                                            <div class="modal-header" style="background-color: rgba(240, 0, 0, 0.85);border-top-left-radius:10px;border-top-right-radius:10px;">
                                                                <h5 class="modal-title" id="exampleModalLongTitle" style="font-size:25px">Remove Consultation</h5>
                                                                <button type="button" class="close" onclick="CloseDelete('@item.Id')" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <h3> Are you sure you want to delete this consultation?</h3>
                                                                <h4>Title:  @item.Title</h4>
                                                                <h4>Patient: @item.Patient.DisplayName</h4>
                                                            </div>
                                                            <div class="modal-footer " style="background-color: rgba(255, 0, 0, 0.8);border-bottom-left-radius:10px;border-bottom-right-radius:10px;">
                                                                <div style="text-align:center;display:inline-block;width:100%">
                                                                    <form asp-action="Delete">
                                                                        <input type="hidden" value="@item.Id" name="Id" />
                                                                        <button class="btn btn-primary">Yes</button>
                                                                    </form>
                                                                  
                                                                    <button class="btn btn-danger" onclick="CloseDelete('@item.Id');">No</button>
                                                                </div>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        <div class="modal-footer">
                                        </div>
                                    </div>
                                </div>
                                </div>
                            
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>




<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script type="text/javascript">
    function Show(id) {
        $("#" + id).modal();
        }
    function Remove(id) {
          $("#C" + id).modal();
        }
    function CloseDelete(id) {
        $("#C"+id).modal('hide');
    }
</script>

<style>
    .modal-header {
        background-color: rgba(0,0, 250, 0.85);
        color: white;
        text-align: left;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
    }

    .modal-body {
        background-color: rgba(255,255,255,1);
    }

    .modal-footer {
        background-color: rgba(0,0, 255, 0.8);
        color: white;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .modal-content {
        background-color: rgba(255,255, 255, 0.1);
        box-shadow: 0 8px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;
    }

    .modal-backdrop {
        background-color: initial;
    }


    .a2, .a2:after {
        color: blue;
    }

        .a2:hover {
            color: dodgerblue;
        }
</style>