FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FleetManagementWebApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FleetManagementWebApplication.Controllers
{
    public class ReportsController : FleetController
    {
        
        public  ReportsController(ApplicationDbContext context)
      :base(context)
        {  
        }

        public IActionResult DriversEvolution(DateTime d1,DateTime d2 )

        {

            if(!LogedIn())
                return RedirectToRoute("Home");
            if(d1 == DateTime.MinValue)
            {
                d1 = DateTime.Parse("2018/1/1");
            }

            if (d2 == DateTime.MinValue)
            {
                d2 = DateTime.Parse("2019/2/1");
            }

            var query = from summary in _context.DeliverySummaries
                        where (summary.StartTime >=d1 && summary.StartTime<=d2 
                                      && summary.Delivery.Company.Id==CompanyId)
                        group summary by summary.StartTime into g
                        select new
                        {
                            Date = g.Key,
                            AveragePerformance = g.Average(summary => summary.PerformanceScore),
                            AverageCompliance = g.Average(summary => summary.ComplianceScore),
                            AverageSafety = g.Average(summary => summary.SafetyScore)
                        };

            DateTime[] date = new DateTime[query.Count()];
            float[] performance = new float[date.Length];
            float[] compliance = new float[date.Length];
            float[] safety = new float[date.Length];
            int i = 0;
            foreach(var summary in query)
            {
                date[i] = summary.Date;
                performance[i] = summary.AveragePerformance;
                compliance[i] = summary.AverageCompliance;
                safety[i] = summary.AverageSafety;
                i++;
             }

            ViewData["Date"] = date;
            ViewData["Performance"] = performance;
            ViewData["Compliance"] = compliance;
            ViewData["Safety"] = safety;
            ViewData["d1"] = d1.ToString("yyyy-MM-dd");
            ViewData["d2"] = d2.ToString("yyyy-MM-dd"); ;


            return View();
        }

        public IActionResult DriversRanks()
        {
            if (!LogedIn())
                return RedirectToRoute("Home");
          
            Driver[] drivers = _context.Drivers.Where(d => d.Company.Id == CompanyId)
                                        .OrderBy(d => d.Rank).ToArray();
            return View(drivers);
        }


        public IActionResult Costs(DateTime d1, DateTime d2)
        {
            if (!LogedIn())
                return RedirectToRoute("Home");

            if (d1 == DateTime.MinValue)
            {
                d1 = DateTime.Parse("2018/1/1");
            }

            if (d2 == DateTime.MinValue)
            {
                d2 = DateTime.Now;
            }

            var query = from bill in _context.Bills
                        where (bill.DateTime >= d1 && bill.DateTime <= d2 && bill.Vehicle.Company.Id == CompanyId)
                        group bill by bill.Service into g
                        select new
                        {
                            Service = g.Key,
                            Cost = g.Sum(bill =>bill.Cost)
                       };

            string[] services = new string [query.Count()];
            float[] costs = new float[services.Length];
            
            int i = 0;
            foreach (var b in query)
            {
                services[i] = b.Service;
                costs[i] = b.Cost;
               i++;
            }

            ViewData["services"] = services;
            ViewData["costs"] = costs;            
            ViewData["d1"] = d1.ToString("yyyy-MM-dd");
            ViewData["d2"] = d2.ToString("yyyy-MM-dd"); ;


            return View();
        }


        public IActionResult FuelConsumption(int year=2018)
        {
            if (!LogedIn())
                return RedirectToRoute("Home");

            var query = from summary in _context.DeliverySummaries
                        join d in _context.Deliveries on summary.Delivery.Id equals d.Id
                        where d.Company.Id == CompanyId && summary.StartTime.Year==year
                        group new { summary, d } by   new { summary.StartTime.Month}  into g
                        select new
                        {
                            Month = g.Key,
                            ActualFuel = g.Sum(p => (p.summary.StartFuelLevel -p. summary.EndFuelLevel)),
                            OptimizedFuel= g.Sum(p=>p.d.OptimalFuelConsumption)
                       };

            var query1 = from summary in _context.DeliverySummaries
                         where summary.Delivery.Company.Id == CompanyId && summary.StartTime.Year == year
                         group  summary  by summary.StartTime.Month  into g
                        select new
                        {
                            Month = g.Key,
                            Score=g.Average(summary=>(summary.PerformanceScore+summary.SafetyScore+summary.ComplianceScore)/3)
                        };




            int[] months = new int[query.Count()];
           float[] optimFuel = new float[months.Length];
           float[] actFuel = new float[months.Length];
            float[] score = new float[months.Length];
            int i = 0;
            foreach(var s in query)
            {
                months[i] = s.Month.Month;
                optimFuel[i] = s.OptimizedFuel;
                actFuel[i] = s.ActualFuel;
                i++;
            }
            i = 0;
            foreach (var s in query1)
            {
                score[i] = s.Score;
                i++;
            }

            ViewData["months"] = months;
            ViewData["optimFuel"] = optimFuel;
            ViewData["actFuel"] = actFuel;
            ViewData["score"] = score;
           
            return View();
        }



    }
}

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Reports/Costs.cshtml
@{
    ViewData["Title"] = "Drivers Evolution";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
string[] services = (string[])ViewData["services"];
    float[] costs = (float[])ViewData["costs"];
var YCosts = Newtonsoft.Json.JsonConvert.SerializeObject(costs);
    var XServices= Newtonsoft.Json.JsonConvert.SerializeObject(services);
}
<!-- Styles -->
<style>
    #chartdiv {
        width: 100%;
        height: 500px;
    }

    input[type='date'] {
        width: 80%
    }
    .box {
        top: 10px;
    }
</style>

<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/material.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<link rel="stylesheet" href="~/css/Style.css" />


<body>
    <div class="box-wrapper">
        <div class="box effect6" style="width:80%">
            <form asp-controller="Reports" asp-action="Costs" method="get">
                <table width="90%">
                    <tr>
                        <td><h3>Costs Evalution </h3></td>
                        <td align="right">
                            <input type="date" name="d1" />
                        </td>
                        <td align="right"><input type="date" name="d2" /></td>
                        <td>
                            <input type="submit" value="GO" />
                        </td>
                    </tr>
                </table>
            </form>
            <div class="w3-container w3-padding">

                @if (costs.Length == 0)
                {
                    <center><h4 style="color:darkcyan">Nothing to show</h4></center>
                }
                <!-- Chart code -->
                <script>

                am4core.ready(function () {

                    // Themes begin
                    am4core.useTheme(am4themes_animated);
                    am4core.useTheme(am4themes_material);
                    // Themes end

                    var chart = am4core.create("chartdiv", am4charts.PieChart3D);
                    chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

                    chart.legend = new am4charts.Legend();
                    var services = @Html.Raw(XServices);
                    var costs =@YCosts;

                    chart.data = Array(services.length);
                    for (var i = 0; i < services.length; i++) {
                        chart.data[i] =
                            {
                                service: services[i],
                                cost: costs[i]
                            }
                            ;
                    }
                    var series = chart.series.push(new am4charts.PieSeries3D());
                    series.dataFields.value = "cost";
                    series.dataFields.category = "service";

                }); // end am4core.ready()
                </script>

                <!-- HTML -->
                <div id="chartdiv"></div>

            </div>
        </div>
        <br />
        <br />
        </div>
</body>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Reports/DriversEvolution.cshtml
@{
    ViewData["Title"] = "Drivers Evolution";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
    DateTime[] Date = (DateTime[])ViewData["Date"];
    float[] Performance = (float[])ViewData["Performance"];
    float[] Compliance = (float[])ViewData["Compliance"];
    float[] Safety = (float[])ViewData["Safety"];
    int[] Years = new int[Date.Length];
    int[] Months = new int[Date.Length];
    int[] Days = new int[Date.Length];
    DateTime d;
    for (int i = 0; i < Date.Length; i++)
    {
        d = Date[i];
        Years[i] = d.Year;
        Months[i] = d.Month;
        Days[i] = d.Day;
    }
    var d1 = ViewData["d1"];
    var d2 = ViewData["d2"];


    var YPerformance = Newtonsoft.Json.JsonConvert.SerializeObject(Performance);
    var YSafety = Newtonsoft.Json.JsonConvert.SerializeObject(Safety);
    var YCompliance = Newtonsoft.Json.JsonConvert.SerializeObject(Compliance);
    var XDays = Newtonsoft.Json.JsonConvert.SerializeObject(Days);
    var XMonths = Newtonsoft.Json.JsonConvert.SerializeObject(Months);
    var XYears = Newtonsoft.Json.JsonConvert.SerializeObject(Years);


    //ViewData["Title"] = "Bar Chart";
}
<head>
    <title>Drivers Evolution</title>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js"></script>
    <link rel="stylesheet" href="~/css/Style.css" />

</head>

<style>
    input[type='date'] {
        width: 80%
    }
    .box {
        top: 10px;
    }
</style>

<body>
    <div class="box-wrapper">
        <div class="box effect6" style="width:80%">
            <form asp-controller="Reports" asp-action="DriversEvolution" method="get">
                <table width="90%">
                    <tr>
                        <td><h3>Drivers Evolution</h3></td>
                        <td align="right">
                            <input type="date" name="d1" value="@d1" />
                        </td>
                        <td align="right"><input type="date" name="d2" value="@d2" /></td>
                        <td>
                            <input type="submit" value="GO" />
                        </td>
                    </tr>
                </table>
            </form>
            <div class="w3-container w3-padding">

                <canvas id="chartCanvas"></canvas>

                <script>
                var Days =@XDays;
                var Months =@XMonths;
                var Years =@XYears;
                var dates = Array(Months.length);
                for (var i = 0; i < dates.length; i++) {
                    dates[i] = new Date(Years[i], Months[i], Days[i]);
                }

                const ctx = document.getElementById('chartCanvas').getContext('2d');
                const data = {
                    // Labels should be Date objects
                    labels:dates,
                    datasets: [{
                        fill: false,
                        label: 'Perormane Score',
                        data:@YPerformance,
                        borderColor: 'red',
                        backgroundColor: 'red'
                    },
                    {
                        fill: false,
                        label: 'Compliance Score',
                        data: @YCompliance,
                        borderColor: 'blue',
                        backgroundColor: 'blue'

                    },
                    {
                        fill: false,
                        label: 'Safety Score',
                        data: @YSafety,
                        borderColor: 'green',
                        backgroundColor: 'green'

                    }]
                }
                const options = {
                    type: 'line',
                    data: data,
                    options: {
                        fill: false,
                        responsive: true,
                        scales: {
                            xAxes: [{
                                type: 'time',
                                display: true,

                                scaleLabel: {
                                    display: true,
                                    labelString: "Date",
                                },
                                minRotation: 30
                            }],
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true,
                                },
                                display: true,
                                scaleLabel: {
                                    display: true,
                                    labelString: "Page Views",
                                }
                            }]
                        }
                    }
                }
                const chart = new Chart(ctx, options);




                </script>


            </div>
        </div>
        <br />
        <br />
        </div>
</body>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Reports/DriversPerformance.cshtml
@model IEnumerable<FleetManagementWebApplication.Models.Driver>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
}
    <div class="box-wrapper">
        <div class="box effect6">
            <h3>Drivers Ranks</h3>
            <div class="w3-container w3-padding">
                <center>
                    @foreach (Driver d in (Driver[])Model)
                    {
                        <table width="500px" cellspacing="0px" class='table3'>
                            <tr>
                                <td rowspan="3">
                                    <div class="div5">
                                        <img src="~/images/t.jpg" width='100' height='80' />
                                    </div>
                                </td>
                                <td>
                                    <h1>Rank @d.Rank</h1>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Name : @d.Name
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Score: @d.Score
                                </td>
                            </tr>
                        </table>
                        <br />
                    }

                </center>
                </div>
            </div>
        </div>

                <style>

                    .div5 {
                        border-color: yellow;
                        border-radius: 100px;
                        background-color: white;
                        text-align: center;
                        height: 140px;
                        font-size: 40px;
                        width: 140px;
                        padding: 30px 26px;
                        margin: 8px 0;
                        box-sizing: border-box;
                    }

                    .table3 {
                        border-radius: 40px;
                        border-color: #990033;
                        border-width: 10px;
                        font-size: 20px;
                        padding: 15px 20px;
                        background-color: #f2f2f2;
                    }
                 .box {
                        text-align: left;
                        position: relative;
                        top: 12px;
                        padding: 10px 30px;
                        width: 60%;
                        padding-bottom: 30px;
                        background: #FFF;
                    }

                   
                     
                </style>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Reports/DriversRanks.cshtml
@model IEnumerable<FleetManagementWebApplication.Models.Driver>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutManager.cshtml";
}
<link rel="stylesheet" href="~/css/Style.css" />
<style>
       .box{
            top:20px;
            width:800px;
            margin-bottom:50px;
        }
</style>
<div class="box-wrapper">
    <div class="box effect6">
        <h3>Drivers Ranks</h3>
        <div class="w3-container w3-padding">
            <center>
                @foreach (Driver d in (Driver[])Model)
                {
                    <table width="90%" cellspacing="0px" class='table3'>
                        <tr>
                            <td style="width:15%;padding:5px 10px;">
                                <div>
                                    <img src="~/images/@d.Image" width='70' height='70' />
                                </div>
                            </td>
                            <td style="font-size:20px;vertical-align:middle;width:65%;padding:10px 20px;">

                                <span style="color:grey"> Name: </span><span style="color:brown"> @d.Name</span><br />
                                <span style="color:grey">  Score:  </span> <span style="color:red"> @d.Score</span>
                            </td>
                            <td>
                                <span class="round" style="color:yellow">Rank @d.Rank</span><br />
                            </td>
                        </tr>
                    </table>
                    <br />
                }

            </center>

</div>
</div>
</div>

FleetManagementSystem/FleetManagementWebApplication/FleetManagementWebApplication/Views/Reports/FuelConsumption.cshtml
@using System.Linq
@{
    ViewData["Title"] = "Drivers Evolution";
    Layout = "~/Views/Shared/LayoutManager.cshtml";

    int[] months=(int[])ViewData["months"];
    float[] optimFuel=(float[])ViewData["optimFuel"];
    float[] actFuel=(float[])ViewData["actFuel"];
    float[] score=(float[])ViewData["score"];
    if (actFuel.Length>0)
    {
        float max=actFuel.Max() ;
        for(int i=0;i<score.Length;i++)
        {
            score[i]=(score[i]*max)/5;
        }
    }

    var XMonths = Newtonsoft.Json.JsonConvert.SerializeObject(months);
    var YOptim = Newtonsoft.Json.JsonConvert.SerializeObject(optimFuel);
    var YAct = Newtonsoft.Json.JsonConvert.SerializeObject(actFuel);
    var YScore = Newtonsoft.Json.JsonConvert.SerializeObject(score);


}
<head>
    <title>Drivers Evolution</title>

    <link rel="stylesheet" href="~/css/Style.css" />
    <title>Combo Bar-Line Chart</title>
    <script src="https://www.chartjs.org/samples/latest/utils.js"></script>
    <script src="https://www.chartjs.org/dist/2.8.0/Chart.min.js"></script>

    <style>
        canvas {
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }
        .box{
            top:10px;
        }
    </style>
</head>


<body>
    <div class="box-wrapper">
        <div class="box effect6" style="width:80%">
            <form asp-controller="Reports" asp-action="FuelConsumption" method="get">
                <table width="90%">
                    <tr>
                        <td><h3>Fuel Consumption </h3></td>
                        <td align="right">
                            <input type="number" name="year" />
                        </td>

                        <td>
                            <input type="submit" value="GO" />
                        </td>
                    </tr>
                </table>
            </form>
            <div class="w3-container w3-padding">

                <div>
                    <canvas id="canvas"></canvas>
                </div>

                <script>
                var MonthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'November', 'December'];
                var Months =@XMonths;
                var Labels = Array(Months.length);
                for (var i = 0; i < Months.length; i++) {
                    Labels[i] = MonthNames[Months[i]-1];
                 }
                var chartData = {
                    labels: Labels,
                    datasets: [{
                        type: 'line',
                        label: 'Drivers performance',
                        borderColor: window.chartColors.blue,
                        borderWidth: 2,
                        fill: false,
                        data:@YScore
                    }, {
                        type: 'bar',
                        label: 'Optimal fuel consumption',
                        backgroundColor: window.chartColors.red,
                        data: @YOptim,
                        borderColor: 'white',
                        borderWidth: 2,



                    }, {
                        type: 'bar',
                        label: 'Actual fuel consumption',
                        backgroundColor: window.chartColors.green,
                        data:@YAct
                    }]

                };
                window.onload = function () {
                    var ctx = document.getElementById('canvas').getContext('2d');
                    window.myMixedChart = new Chart(ctx, {
                        type: 'bar',
                        data: chartData,
                        options: {
                            responsive: true,
                            title: {
                                display: false,
                                text: 'Fuel Consumption Graph'
                            },
                            tooltips: {
                                mode: 'index',
                                intersect: true
                            },
                            plugins: {
                                datalabels: {
                                    anchor: 'end',
                                    align: 'top',
                                    formatter: Math.round,
                                    font: {
                                        weight: 'bold'
                                    }
                                }
                            }

                        }
                    });
                };


                </script>




            </div>
        </div>
        <br />
        <br />
        </div>
</body>