Clinic/Clinic/Models/InsuranceCompany.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Clinic.Models
{
    public class InsuranceCompany
    {
        [Required]
        public long Id { get; set; }
   
        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        public string Address { get; set; }
        [StringLength(100)]
        public string Fax { get; set; }
        [StringLength(100)]
        public string Image { get; set; }
      
        public IdentityUser User { get; set; }
        public List<Patient> Patients { get; set; }
        public List<Report> Reports { get; set; }
        
   

    }
}

Clinic/Clinic/Controllers/InsuranceCompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clinic.Data;
using Clinic.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Clinic.Controllers
{
    public class InsuranceCompaniesController : ClinicController
    {

        public readonly IHostingEnvironment _environment;
        public InsuranceCompaniesController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IHostingEnvironment environment)
        : base(context, userManager)
        {
            _environment = environment;
        }
        [Authorize(Policy ="Insurance")]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Authorize(Roles="Admin")]
            public async Task<IActionResult> Search(SearchInsurance search)
        {

            var query = _context.InsuranceCompanies.Include(d => d.User).Where(i=>i.Id>0).ToArray();
            if (search.SearchId != 0)
            {
                search.InsuranceCompanies = query.Where(d => d.Id == search.SearchId).ToArray();
                return View(search);
            }
            if (search.Name != null)
                query = query.Where(d => d.Name == search.Name).ToArray();
            if (search.Email != null)
                query = query.Where(d => d.User.Email == search.Email).ToArray();
            if (search.Address != null)
                query = query.Where(d => d.Address.Contains(search.Address)).ToArray();
            if (search.Order == "desc")
                query = query.OrderByDescending(d => d.Name).ToArray();
            else
                query = query.OrderBy(d => d.Name).ToArray();
            search.InsuranceCompanies = query;
            return View(search);
        }

        [Authorize(Roles = "Insurance")]
        public async Task<IActionResult> Profile()
        {
            string id = _userManager.GetUserId(User);
            var insurance = await _context.InsuranceCompanies.Include(i=>i.User).FirstOrDefaultAsync(i=> i.User.Id == id);
            if (insurance == null)
            {
                return NotFound();
            }

            return View(insurance);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
                   return View();
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(RegisterInsuranceCompany registerInsuranceCompany, IFormFile file)
        {
            if (_userManager.Users.Any(u => u.UserName == registerInsuranceCompany.Username))
            {
                ModelState.AddModelError(String.Empty, "User name already taken");
                ViewData["message"] = "Already Taken";
                return View(registerInsuranceCompany);
            }

            if (ModelState.IsValid)
            {
                if(_context.InsuranceCompanies.Any(i=>i.User.UserName==registerInsuranceCompany.Username))
                {
                    ViewData["message"] = "Already Taken";
                    return View(registerInsuranceCompany);
                }

               

                string image = "";
                if (file != null)
                {
                    var filePath = Path.GetTempFileName();
                    using (FileStream filestream = System.IO.File.Create(_environment.WebRootPath + "\\images\\" + file.FileName))
                    {
                        image = file.FileName;
                        file.CopyTo(filestream);
                        filestream.Flush();
                    }
                }
             
                var user = new IdentityUser
                {
                    UserName = registerInsuranceCompany.Username,
                    Email = registerInsuranceCompany.Email,
                    PhoneNumber=registerInsuranceCompany.Phone
                };
                var result = await _userManager.CreateAsync(user, registerInsuranceCompany.Password);
                await _userManager.AddClaimAsync(user, new Claim(ClaimTypes.Role, "Insurance"));

                InsuranceCompany company = new InsuranceCompany
                {
                    Name = registerInsuranceCompany.Name,
                    Address = registerInsuranceCompany.Address,
                    Fax = registerInsuranceCompany.Fax,
                    Image = image,
                    User = user
                };
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Search));
            }
            ViewData["error"] = "error";
            return View(registerInsuranceCompany);
        }

        [Authorize(Roles = "Admin,Insurance")]
        public async Task<IActionResult> Edit(long id)
        {
            InsuranceCompany insuranceCompany = null;

            if (User.IsInRole("Insurance"))
               insuranceCompany=_context.InsuranceCompanies.Include(i=>i.User).Where(i=>i.User.Id==_userManager.GetUserId(User)).Single();
              else
             insuranceCompany = _context.InsuranceCompanies.Include(i => i.User).Single(i=>i.Id==id);

            if (insuranceCompany == null)
            {
                return NotFound();
            }
            EditInsuranceCompany model = new EditInsuranceCompany
            {
                Id = insuranceCompany.Id,
                Name =insuranceCompany.Name,
                Address = insuranceCompany.Address,
                Fax = insuranceCompany.Fax,
                Image =insuranceCompany.Image,
                Username=insuranceCompany.User.UserName,
                Email=insuranceCompany.User.Email,
                Phone=insuranceCompany.User.PhoneNumber
            };
            return View(model);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Insurance")]
        public async Task<IActionResult> Edit(long id, EditInsuranceCompany model,IFormFile file)
        {
            string returnAction = "Search";
            if (_userManager.Users.Any(u => u.UserName == model.Username))
            {
                ModelState.AddModelError(String.Empty, "User name already taken");
                return View(model);
            }
            if (id != model.Id)
            {
                return NotFound();
            }

            InsuranceCompany company = _context.InsuranceCompanies.Include(i => i.User).Single(i => i.Id == id);
          
            if (ModelState.IsValid)
            {
                try
                {
                    IdentityUser user = company.User;
                    var username = await _userManager.GetUserNameAsync(user);
                    if (model.Username != username)
                    {
                        if (_userManager.Users.Any(u => u.UserName == model.Username))
                        {
                            ModelState.AddModelError(String.Empty, "User name already taken");
                            return View(model);
                        }
                        var setUserNameResult = await _userManager.SetUserNameAsync(user, model.Username);

                        if (!setUserNameResult.Succeeded)
                        {
                            var userId = await _userManager.GetUserIdAsync(user);
                            throw new InvalidOperationException($"Unexpected error occurred setting username for user with ID '{userId}'.");
                        }
                    }

                    if (file != null)
                    {
                        var filePath = Path.GetTempFileName();
                        using (FileStream filestream = System.IO.File.Create(_environment.WebRootPath + "\\images\\" + file.FileName))
                        {
                            model.Image = file.FileName;
                            file.CopyTo(filestream);
                            filestream.Flush();
                        }
                    }

                    company.Name = model.Name;
                company.Address = model.Address;
               company.Fax = model.Fax;
                company.Image = model.Image;

                   

                    var email = await _userManager.GetEmailAsync(user);
                    if (model.Email != email)
                    {
                        var setEmailResult = await _userManager.SetEmailAsync(user, model.Email);

                        if (!setEmailResult.Succeeded)
                        {
                            var userId = await _userManager.GetUserIdAsync(user);
                            throw new InvalidOperationException($"Unexpected error occurred setting email for user with ID '{userId}'.");
                        }
                    }

                    var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
                    if (model.Phone != phoneNumber)
                    {
                        var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, model.Phone);
                        if (!setPhoneResult.Succeeded)
                        {
                            var userId = await _userManager.GetUserIdAsync(user);
                            throw new InvalidOperationException($"Unexpected error occurred setting phone number for user with ID '{userId}'.");
                        }
                    }
                    company.User = user;

                    _context.InsuranceCompanies.Update(company);
                    await _context.SaveChangesAsync();
                }

Clinic/Clinic/Views/InsuranceCompanies/Create.cshtml
@model Clinic.Models.RegisterInsuranceCompany

@{
    ViewData["Title"] = "Create";

}


<link rel="stylesheet" href="~/css/window.css" />
<div class="window-wrapper">
    <div class="window">
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="header">
                Create Insurance Company's Profile
                <a href="/home" class="btn-X">X</a>
            </div>
            <div class="body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-lg-4 ">
                        <div class="column">
                            <h3>Account Information</h3>
                            <div class="form-group">
                                <label asp-for="Username" class="control-label"></label>
                                <input asp-for="Username" class="form-control" value="@ViewData["in_id"]" />
                                <span asp-validation-for="Username" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="@Model.Email"></label>
                                <input asp-for="@Model.Email" class="form-control" />
                                <span asp-validation-for="@Model.Email" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="@Model.Password"></label>
                                <input asp-for="@Model.Password" class="form-control" />
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="@Model.ConfirmPassword"></label>
                                <input asp-for="@Model.ConfirmPassword" class="form-control" />
                                <span asp-validation-for="@Model.ConfirmPassword" class="text-danger"></span>
                            </div>

                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="column">
                            <h3>Company Information</h3>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Phone" class="control-label"></label>
                                <input asp-for="Phone" class="form-control" />
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Address" class="control-label"></label>
                                <input asp-for="Address" class="form-control" />
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Fax" class="control-label"></label>
                                <input asp-for="Fax" class="form-control" />
                                <span asp-validation-for="Fax" class="text-danger"></span>
                            </div>


                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="column">
                            <h3>Company's Image</h3>
                            <br />
                            <div class="form-group">
                                <div class="pt-img">
                                    <img id="blah" src="~/images/company.png" width="100%" height="100%" style="border-radius:20px;" />
                                </div>
                                <br />
                                <br />
                                <center>
                                    <input type='file' onchange="readURL(this);" name="file" id="file" class="inputfile" />

                                    <label for="file">choose an image</label>
                                </center>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer" style="padding-bottom:5px;">

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>

<h1>@ViewData["Error"]</h1>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    ;
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Clinic/Clinic/Views/InsuranceCompanies/Index.cshtml
<style>
    body, html {
        height: 100%;
    }
</style>

Clinic/Clinic/Views/InsuranceCompanies/Profile.cshtml
@model Clinic.Models.InsuranceCompany

@{
    ViewData["Title"] = "Create";

}

<link rel="stylesheet" href="~/css/window.css" />
<div class="window-wrapper">
    <div class="window">
            <div class="header">
             Profile
                <a href="/home" class="btn-X">X</a>
            </div>
            <div class="body">
                <div class="row">
                    <div class="col-lg-7">
                        <h2>@Model.Name</h2>
                        <div>Id: @Model.Id</div>
                        <div>Username: @Model.User.UserName</div>
                        <div>Email: @Model.User.Email</div>
                        <div>Phone: @Model.User.PhoneNumber</div>
                        <div>Address: @Model.Address</div>
                    </div>
                    <div class="col-lg-5">
                        <img src="~/images/@Model.Image" width="250" height="250" style="border-radius:5px;" />
                    </div>

                    <div class="col-lg-5">
                        <br />
                        <br />
                    

                    </div>
                </div>
            </div>
            <div class="footer">

                <form asp-action="Edit" method="get">
                    <input type="submit" value="Edit" class="btn btn-success" />
                </form>
                
               

            </div>

                </div>
            </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clinic/Clinic/Views/InsuranceCompanies/Search.cshtml
@model SearchInsurance

@{
    ViewData["Title"] = "Search";
    SelectListItem Asc = new SelectListItem() { Value = "asc", Text = "Ascending" };
    SelectListItem Desc = new SelectListItem() { Value = "desc", Text = "Descending" };
    if (Model.Order == "desc")
    {
        Desc.Selected = true;
    }
    else
    {
        Asc.Selected = true;
    }
    SelectListItem[] Orders = { Asc, Desc };
    var X = "";
    if (Model.SearchId != 0)
    {
        X = "" + Model.SearchId;
    }


}
    <style>

      
    .window {
        width: initial;
    }

    .col-lg-9 {
        padding-left: 10px;
    }

    .col-lg-3 {
        text-align: left;
    }
</style>
<div class="window-wrapper" style="padding-top:10px;">
    <div style="text-align:left;display:inline-block;min-width:80%;">
        <div class="row">
            <div class="col-lg-3 col-md-3 ">
                <div class="window">
                    <form asp-action="Search" method="get">
                        <div class="header">
                            Search Companies
                        </div>
                        <div class="body" style="padding-left:10px;padding-right:10px;">
                            <div class="form-group">
                                <label class="control-label">Company Id</label>
                                <input asp-for="SearchId" class="form-control" type="text" value="@X" />
                            </div>
                            <div class="form-group">
                                <label class="control-label"> Name</label>
                                <input asp-for="Name" class="form-control" value="@Model.Name" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Email</label>
                                <input asp-for="Email" class="form-control" value="@Model.Email" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Address</label>
                                <input asp-for="Address" class="form-control" value="@Model.Address" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Order</label>
                                <select asp-for="Order" class="form-control ss" asp-items="@Orders"></select>
                            </div>
                        </div>
                        <div class="footer">
                            <button type="submit" class="btn btn-success">Search</button>
                        </div>
                    </form>
                </div>

            </div>
            <div class="col-lg-9 col-md-9 ">
                <div class="window" style="width:100%;">
                    <div class="header">
                        Results
                    </div>
                    <div class="body" style="min-height:470px;">
                        <div style="font-size:15px;padding-bottom:10px;">Click on any search entry to view the profile of the company</div>

                        @foreach (var item in Model.InsuranceCompanies)
                        {

                            <form   onclick="Show(@item.Id);">
                                <div class="srch-div" style="width:90%;margin-bottom:3px;">
                                    <table style="width:100%">
                                        <tr>
                                            <td style="width:20%">
                                                <img src="~/images/@item.Image" class="srch-img" />
                                            </td>
                                            <td>
                                                <div style="padding-left:20px;padding-bottom:5px;padding-top:5px;font-size:15px;">

                                                    <div style="font-size:20px;color:rgb(0,0,250);">@Html.DisplayFor(modelItem => item.Name)</div>

                                                    Company Id: @item.Id
                                                    <br />
                                                    Name: @Html.DisplayFor(modelItem => item.Name)
                                                    <br>
                                                    Phone Number:  @Html.DisplayFor(modelItem => item.User.PhoneNumber)
                                                    <br />
                                                    Address: @item.Address
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </form>
                            <div class="modal fade" id="@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle" style="font-size:25px">Company's Profile</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body" style="padding-bottom:40px;">
                                            <div class="row">
                                                <div class="col-lg-7">
                                                    <h2>@item.Name</h2>
                                                    <div>Id: @item.Id</div>
                                                    <div>Username: @item.User.UserName</div>
                                                    <div>Email: @item.User.Email</div>
                                                    <div>Phone: @item.User.PhoneNumber</div>
                                                    <div>Address: @item.Address</div>
                                                </div>
                                                <div class="col-lg-5">
                                                    <img src="~/images/@item.Image" width="250" height="250" style="border-radius:5px;" />
                                                </div>

                                                <div class="col-lg-5">
                                                    <br />
                                                    <br />
                                                    <a asp-controller="InsuranceCompanies" asp-action="Edit" class="a2" asp-route-id="@item.Id">Edit Profile</a><br />
                                                    <a href="javascript:void(0)" class="a2" onclick="Remove('@item.User.Id')" ;">Remove Insurance Company</a>

                                                </div>
                                            </div>
                                            <div class="modal fade" id="@item.User.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered" role="document">
                                                    <div class="modal-content" style="border-radius:10px;">
                                                        <div class="modal-header" style="background-color: rgba(240, 0, 0, 0.85);border-top-left-radius:10px;border-top-right-radius:10px;">
                                                            <h5 class="modal-title" id="exampleModalLongTitle" style="font-size:25px">Remove Assistant</h5>
                                                            <button type="button" class="close" onclick="CloseDelete('@item.User.Id')" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <h3> Are you sure you want to delete this company?</h3>
                                                            <h4>Name:  @item.Name</h4>
                                                            <h4>Assistant Id: @item.Id</h4>
                                                        </div>
                                                        <div class="modal-footer " style="background-color: rgba(255, 0, 0, 0.8);border-bottom-left-radius:10px;border-bottom-right-radius:10px;">
                                                            <div style="text-align:center;display:inline-block;width:100%">
                                                                <form asp-action="Delete" method="post">
                                                                    <button class="btn btn-primary">Yes</button>
                                                                    <input type="hidden" name="Id" value="@item.Id" />
                                                                </form>
                                                                <button class="btn btn-danger" onclick="CloseDelete('@item.User.Id');">No</button>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script type="text/javascript">
    function Show(id) {
        $("#" + id).modal();
        }
    function Remove(id) {
          $("#" + id).modal();
        }
    function CloseDelete(id) {
        $("#"+id).modal('hide');
    }
</script>

<style>
    .modal-header {
        background-color: rgba(0,0, 250, 0.85);
        color: white;
        text-align: left;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
    }

    .modal-body {
        background-color: rgba(255,255,255,1);
    }

    .modal-footer {
        background-color: rgba(0,0, 255, 0.8);
        color: white;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .modal-content {
        background-color: rgba(255,255, 255, 0.1);
        box-shadow: 0 8px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;
    }

    .modal-backdrop {
        background-color: initial;
    }


    .a2, .a2:after {
        color: blue;
    }

        .a2:hover {
            color: dodgerblue;
        }
</style>